### ISSUE TITLE
Segmentation fault (core dumped) when using labels in LLDA

### ISSUE THREAD

**Issue by JonAnderRuizColmenares** [bab2min/tomotopy#30] opened 2020-02-19 16:33 UTC
Hello, I am not an expert and I may be very wrong here, but when I try to make a labelled LDA model I am getting 'Segmentation fault (core dumped)' and it may be a bug?

After declaring;
model = tp.LLDAModel(tw=TermWeight.ONE, min_cf=0, rm_top=0, k=20, alpha=0.1, eta=0.01)

If I do not specify labels, as in:

model.add_doc(myDocument) 

instead of 

model.add_doc(myDocument,labels=myLabel) 

I can add all documents and create a working model just fine, but if I try to put the labels, the program gives me the segmentation error while adding the very first document.

I have also been able to create sLDA and LDA models without any single problem.

**Comment by bab2min** [comment] 2020-03-01 16:49
Thank you for reporting the bug.
I found where the problem is and it will be fixed 0.5.2 version.
Please re-try after updating tomotopy to 0.5.2 version.

**Comment by JonAnderRuizColmenares** [comment] 2020-03-02 11:50
Thank you for the work you are doing! :)

**Closed** 2020-03-02 13:04 UTC
Labels: bug
