### ISSUE TITLE
Issue in HDPModel

### ISSUE THREAD

**Issue by lkoneha** [bab2min/tomotopy#6] opened 2019-09-28 17:42 UTC
When I am training HDP model by using tomotopy, while computing log likelihood it is crashing.

**Comment by bab2min** [comment] 2019-09-29 10:20
Could you show details about your problem or a piece of code?
Did train() method work well?

**Comment by lkoneha** [comment] 2019-09-30 06:18
I am using following code:
mdl = tp.HDPModel(tw=tp.TermWeight.IDF)
    x = len(data_lemmatized)
    for k in range(x):
        mdl.add_doc(p[k])

    for i in range(0, 2000, 10):
        mdl.train(10)
        print('Iteration: {}\tLog-likelihood: {}'.format(i, mdl.ll_per_word))


    mdl.save('Dataset3/HDP/hdp_model.bin')

    md = tp.HDPModel.load('Dataset3/HDP/hdp_model.bin')

After running some iterations it is crashing. As shown below it is not completing 2000 iterations:Iteration: 0	Log-likelihood: -27.894216101817914
Iteration: 10	Log-likelihood: -27.75898923561963
Iteration: 20	Log-likelihood: -27.616829459304014
Iteration: 30	Log-likelihood: -27.516104813128543
Iteration: 40	Log-likelihood: -27.430314586882936
Iteration: 50	Log-likelihood: -27.3896103677386
Iteration: 60	Log-likelihood: -27.32694588712716
Iteration: 70	Log-likelihood: -27.277052706515896
Iteration: 80	Log-likelihood: -27.240042890250155
Iteration: 90	Log-likelihood: -27.188211890555234

Process finished with exit code -1073740940 (0xC0000374)

**Comment by bab2min** [comment] 2019-09-30 12:48
It seems definitely tomotopy's problem, but the crashing has not been reproduced, which makes debugging difficult. Could you share the size of your dataset? And could you try following code?

```
mdl = tp.HDPModel(tw=tp.TermWeight.IDF, initial_k=20)
x = len(data_lemmatized)
for k in range(x):
mdl.add_doc(p[k])

for i in range(0, 2000, 10):
    mdl.train(10)
    print('Iteration: {}\tLog-likelihood: {}\tK:{}'.format(i, mdl.ll_per_word, mdl.live_k))
```

I added **initial_k** parameter and logging values of **live_k** to your code. If you share the result of this code, it can be helpful to solve this problem. Thank you in advance.

**Comment by bab2min** [comment] 2019-10-05 10:19
I found the cause of the problem at optimizeParameters function of LDAModel class. The problem will be fixed next update. Please wait. Thank you!

**Closed** 2019-10-06 15:12 UTC
