### ISSUE TITLE
Segfaults with alpha

### ISSUE THREAD

**Issue by ankane** [bab2min/tomotopy#77] opened 2020-10-14 07:12 UTC
Hi @bab2min, just wanted to report some segfaults I came across when building the Ruby library.

```python
import tomotopy as tp

model = tp.GDMRModel()
print(model.alpha)

model = tp.DTModel()
print(model.alpha)
```

tomotopy version: 0.9.1

**Comment by bab2min** [comment] 2020-10-29 05:41
It has been identified as an error caused by accessing uninitialized data. It will be fixed at the next update.
Thank you for your reporting!

**Comment by bab2min** [comment] 2020-12-20 04:08
fixed at version 0.10.0

**Closed by bab2min** 2020-12-20 04:08 UTC
Labels: bug

**Comment by ankane** [comment] 2020-12-20 19:26
Thanks @bab2min, works great!
